### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [1]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [2]:
print(np.zeros(shape=(10)))
print(np.ones(shape=(10)))
print(np.ones(shape=(10)) * 5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [4]:
print(np.arange(30, 71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [6]:
print(np.arange(10, 50, 2))

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [8]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [10]:
print(np.random.random(1))

[0.08278688]


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [11]:
np.random.randn(15)

array([-0.41074113, -0.8856741 ,  0.09110561,  0.41904625,  1.23684442,
       -0.62480295,  0.08691984,  0.29946611,  0.72039099,  0.18487761,
        1.01675688,  0.22849799,  0.98152031,  2.11129092, -1.60631912])

###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [14]:
array  = np.random.randint(100, size = (3, 4))

print(array)

for i in array:
    for j in i:
        print(j, end=' ')

[[74 57 14 65]
 [70 18 10  3]
 [50 97 86 49]]
74 57 14 65 70 18 10 3 50 97 86 49 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [17]:
vec1 = np.array([1, 8, 3, 5])
vec2 = np.array([10, 1, 4, 10])

vec1 * vec2

array([10,  8, 12, 50])

###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [19]:
np.array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37])[::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [22]:
np.arange(1,6) * np.identity(5, dtype= int)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [26]:
array = np.array([[0, 1], [2, 3]])

print(f'original array \n {array}')
print(f'Sum of all elements \n {array.sum()}')
print(f'Sum of each column: \n {array.sum(axis = 0)}')
print(f'Sum of each row: \n {array.sum(axis = 1)}')

original array 
 [[0 1]
 [2 3]]
Sum of all elements 
 6
Sum of each column: 
 [2 4]
Sum of each row: 
 [1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [32]:
vec1 = np.array([4, 5])
vec2 = np.array([7, 10])


vec1.dot(vec2)

78