### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [1]:
import numpy as np

In [2]:
array = np.array([[3,6, np.nan,5 ],[4,np.nan,6,2], [np.nan,7,4,3]])

print(f'Original array: \n {array}')
print(f'missing values: \n {np.isnan(array)}')

Original array: 
 [[ 3.  6. nan  5.]
 [ 4. nan  6.  2.]
 [nan  7.  4.  3.]]
missing values: 
 [[False False  True False]
 [False  True False False]
 [ True False False False]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [3]:
mat1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
mat2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

np.array_equal(mat1, mat2)

True

###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [16]:
original_array = np.random.randint(0, high= 10, size= (4,4))

print(f'''Original array:
{original_array}''')

swapped_array = original_array.copy()
swapped_array[0] = original_array[-1]
swapped_array[-1] = original_array[0]

print(f'''New array after swapping first and last rows of the said array:
{swapped_array}''')

Original array:
[[7 4 3 3]
 [5 0 4 9]
 [4 9 1 3]
 [7 3 3 3]]
New array after swapping first and last rows of the said array:
[[7 3 3 3]
 [5 0 4 9]
 [4 9 1 3]
 [7 4 3 3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [17]:
np.array([1,5,2,6,3,7,3])

array([1, 5, 2, 6, 3, 7, 3])

In [23]:
np.array((1,5,2,6,3,7,3))

array([1, 5, 2, 6, 3, 7, 3])

###### 5. Write a NumPy program to find common values between two arrays.

In [26]:
array1 = np.random.randint(0, high= 10, size= (6))
array2 = np.random.randint(0, high= 10, size= (6))

print(f'array1 ----> {array1}')
print(f'array2 ----> {array2}')
print(f'intersection ----> {np.intersect1d(array1, array2)}')



array1 ----> [1 9 0 5 9 2]
array2 ----> [0 3 9 2 8 9]
intersection ----> [0 2 9]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [28]:
original_array = np.random.randint(0, high= 10, size= (3,2))

print(f'''Reshape 3x2
{original_array}''')

print(f'''Reshape 2x3
{np.reshape(original_array, newshape=(2, 3))}
''')


Reshape 3x2
[[9 9]
 [8 5]
 [7 3]]
Reshape 2x3
[[9 9 8]
 [5 7 3]]



###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [31]:
a = np.array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])

print(f'''Original array:
{a}''')
unique_elements, counts_elements = np.unique(a, return_counts=True)
print(f'''Frequency of unique values of the said array:
{np.array([unique_elements, counts_elements])}''')


Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [ ]:
### code here

In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [ ]:
### code here

In [ ]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [ ]:
## code here

In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [ ]:
### code here

###### 12. Write a NumPy program to find the first Monday in May 2017.

In [ ]:
## code here

In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
